"""empty message

Revision ID: 102962c00ae8
Revises: 6235c7eabe10
Create Date: 2022-12-23 10:04:22.146887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102962c00ae8'
down_revision = '6235c7eabe10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
