"""empty message

Revision ID: 28effaca9e3b
Revises: 102962c00ae8
Create Date: 2022-12-23 15:01:55.137596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28effaca9e3b'
down_revision = '102962c00ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
