"""empty message

Revision ID: 3ec34cd1ff31
Revises: a2171ba4df3e
Create Date: 2022-12-22 21:58:57.215545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec34cd1ff31'
down_revision = 'a2171ba4df3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desconto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('forma_pagto', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('valor_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.drop_column('valor_total')
        batch_op.drop_column('forma_pagto')
        batch_op.drop_column('desconto')

    # ### end Alembic commands ###
