"""empty message

Revision ID: a2171ba4df3e
Revises: c6a36bfd7fa9
Create Date: 2022-12-22 21:50:10.429933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2171ba4df3e'
down_revision = 'c6a36bfd7fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
