"""empty message

Revision ID: aa1a5cc3dafb
Revises: 965a3133b914
Create Date: 2022-12-13 16:57:47.814835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1a5cc3dafb'
down_revision = '965a3133b914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('cep')
        batch_op.drop_column('bairro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
