"""empty message

Revision ID: c6a36bfd7fa9
Revises: 5fe0cb7ddb3d
Create Date: 2022-12-22 21:24:17.214285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a36bfd7fa9'
down_revision = '5fe0cb7ddb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', app.models.tables.MyDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcaments', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
