"""empty message

Revision ID: d1121b2701f0
Revises: 47836213eda3
Create Date: 2022-12-13 13:02:14.160713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1121b2701f0'
down_revision = '47836213eda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bairro', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cep', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone2')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'state')
    op.drop_column('users', 'cep')
    op.drop_column('users', 'bairro')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
